language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  ## PHP Copy/Paste Detector
  - curl -o phpcpd.phar https://phar.phpunit.de/phpcpd.phar

script:
  - phpunit tests/ExampleTest.php
  - phpcpd --verbose --min-tokens=20  ./src
